config/routes.rb
Rbg::Application.routes.draw do

   root 'welcome#index'

     resources :prospects, only: [:new, :create]

end

app/models/prospect.rb
class Prospect < ActiveRecord::Base

	validates_presence_of :name, :inquiry

	validate :contact_information_present?

	private 
	def contact_information_present?
		unless phone.present? || email.present?
			errors.add(:base, "You must provide either an email address or phone number to complete this form.")
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
	#new prospects go here
	def new
		@prospect = Prospect.new
	end
	#create the prospect
	def create
		@prospect = Prospect.new(prospect_params)
		if @prospect.save
			redirect_to root_path
			flash[:message] = "Your inquiry has been submitted"
		else
			flash[:error] = "Form submission could not be submitted"
			render :new
		end
	end

	private
	def prospect_params
		params.require(:prospect).permit(:name, :phone, :email, :inquiry)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		#just so routes know where to go. blank controller.
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.erb
<div class="flash">
	<% if flash[:error] %>
		<%=	flash[:error] %>
	<% elsif flash[:message] %>
		<%= flash[:message] %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rbg</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: "/layouts/flash" %>
<%= yield %>

</body>
</html>

app/views/prospects/new.html.erb
<%= form_for @prospect do |f| %>
<div class="formfields">
  <%= f.label :name %>
  <%= f.text_field :name %>
 </div>
<div class="formfields">
  <%= f.label :phone %>
  <%= f.text_field :phone %>
 </div>
<div class="formfields">
  <%= f.label :email %>
  <%= f.text_field :email %>
 </div>
<div class="formfields">
  <%= f.label :inquiry %>
  <%= f.text_area :inquiry, size: "60x12" %>
 </div>
 <div class="submit">
  <%= f.submit "Submit", id: 'submit' %>
 </div>
<% end %>

app/views/welcome/index.html.erb
Welcome to RBG!
<%= link_to('Contact Us', new_prospect_path) %>